"""
Django settings for studentsdb project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

from django.conf import global_settings

# setting from book:
# BASE_DIR = os.path.dirname(os.path.dirname(__file__))

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# from ../students
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't@b!6z&17%f+ljt%#a)vksimhp%=r%!z-b%n5+yc-juntmo3ay'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# from django.contrib.auth
# Application definition

INSTALLED_APPS = (
    'flat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites.models',
    'crispy_forms',
    'registration',
    'social.apps.django_app.default',
    'students',
    'studentsdb',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    # 'students.util.LocalChooseLang',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'studentsdb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [BASE_DIR+'/templates/'],
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
                "students.context_processors.groups_processor",
                # "students.context_processors.lang_processor",
                "studentsdb.context_processors.students_proc",
            ],
        },
    },
]

from django.contrib.auth.context_processors import auth

WSGI_APPLICATION = 'studentsdb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

from .database.db import DATABASES

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR,'..' , 'db.sqlite3'),
#     }
# }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

# LANGUAGE_CODE = 'en-us'
USE_I18N = True

LANGUAGE_CODE = 'uk'

USE_TZ = True

TIME_ZONE = 'UTC'
# TIME_ZONE = 'Europe/Kiev'

USE_L10N = True

LANGUAGES = (
	('pl', 'Polski'),
	('en', 'English'),
	('uk', 'Ukrainian'),
)


# LOCALE_PATHS = (
#     '/data/work/buildouts/python/studentsdb/src/studentsdb/students/locale/uk',
#     '/data/work/buildouts/python/studentsdb/src/studentsdb/students/locale/en',
# )
# LOCALE_PATHS = (
#     os.path.join(BASE_DIR, 'students/locale'),
# )

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# TEMPLATE_CONTEXT_PROCESSORS = \
#     global_settings.TEMPLATE_CONTEXT_PROCESSORS + (
#         "django.core.context_processors.request",
#         "students.context_processors.groups_processor",
#         "studentsdb.context_processors.students_proc",)

# PORTAL_URL = 'http://www.mysite.com'
PORTAL_URL = 'http://localhost:8024'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'..','media')


# email settings
# please, set here you smtp server details and your admin email
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = '/data/work/buildouts/python/studentsdb/src/studentsdb/studentsdb/mylo' # change this to a proper location
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
ADMIN_EMAIL = 's.miletskiy@gmail.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 's.miletskiy@gmail.com'
EMAIL_HOST_PASSWORD = '********'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# ADMIN_EMAIL = 's.miletskiy@gmail.com'
# EMAIL_HOST = 'smtp.mandrillapp.com'
# EMAIL_PORT = '587'
# EMAIL_HOST_USER = 's.miletskiy@gmail.com'
# EMAIL_HOST_PASSWORD = '9l_sUJ5YZLV7yu3SorEW0g'
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False

CRISPY_TEMPLATE_PACK = 'bootstrap3'

LOG_FILE = os.path.join(BASE_DIR, 'studentsdb.log')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'verbose': {
            # 'format': '%(process)d  %(levelname)s  %(asctime)s %(module)s: %(message)s',
            'format': "[%(asctime)s] %(process)d %(levelname)s [%(name)s:%(filename)s:%(lineno)s] %(message)s",
            'datefmt' : "%d-%b-%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s: %(message)s'
        },
    },
    'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': LOG_FILE,
            'formatter': 'verbose'
        },
        'mail_admins': {
            'level': 'INFO',
            'class': 'django.utils.log.AdminEmailHandler',
            # 'email_backend': 'django.core.mail.backends.filebased.EmailBackend',
            'email_backend': 'django.core.mail.backends.console.EmailBackend',
            'include_html': True,
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['null'],
            'propagate': True,
            'level': 'INFO',
        },
        'students.signals': {
            'handlers': ['console','file'],
            'level': 'INFO',
        },
        'students.views.contact_admin': {
            'handlers': ['console', 'mail_admins'],
            'level': 'INFO',
        },
        'email_was_send': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'students.request': {
            'handlers': ['file','console'],
            'level': 'INFO',
            # 'propagate': False,
        },
        # 'django.request': {
        #     'handlers': ['file','console'],
        #     'level': 'DEBUG',
        #     'propagate': True,
        # }
    }
}

REGISTRATION_OPEN = True

ACCOUNT_ACTIVATION_DAYS = 3

LOGIN_URL = 'users:auth_login'
LOGOUT_URL = 'users:auth_logout'

AUTHENTICATION_BACKENDS = (
    # 'social.backends.facebook.FacebookOAuth2',
    'social.backends.facebook.Facebook2OAuth2',
    'django.contrib.auth.backends.ModelBackend',
    )
# from social.backends.facebook import Facebook2AppOAuth2
from social.backends.facebook import Facebook2OAuth2

SOCIAL_AUTH_FACEBOOK_KEY = '571465946336791'
SOCIAL_AUTH_FACEBOOK_SECRET = 'c3460c81d831b0e181b8eec60e9f8c6a'





